### ISSUE TITLE
EXWM inside Xfce?

### ISSUE THREAD

**Issue by aadcg** [tumashu/exwm-x#11]
Hi.  It seems that you run EXWM inside Xfce, am I correct?

How can this be achieved? Have you documented somewhere? Thanks.

**Comment by aadcg** [comment]
I understood how to do it, thanks.

Why do you prefer running EXWM as the WM within a XFCE session over EXWM alone?

**Comment by tumashu** [comment]
I do not use exwm at the moment. just use xfce :-)

```
Why do you prefer running EXWM as the WM within a XFCE session over EXWM alone?
```

maybe because I like xfce :-)

**Comment by aadcg** [comment]
Logical.
