### ISSUE TITLE
Still requires removed owp-lentic

### ISSUE THREAD

**Issue by tarsius** [tumashu/exwm-x#2]
In https://github.com/tumashu/org-webpage/commit/1bbe1da22926e111934e2d2cda1376f2b205f4c4 you removed `owp-lentic.el`, but `exwm-x-devtools.el` still requires it

**Comment by tumashu** [comment]
thanks, i will fix it

**Comment by tumashu** [comment]
Fixed, but el2org need installed manual at the moment before its recipe is merged to melpa.

**Comment by tarsius** [comment]
Thanks!
