### ISSUE TITLE
Features are (no longer) available owp-el2org and owp-web-server

### ISSUE THREAD

**Issue by tarsius** [tumashu/exwm-x#4]
`exwm-x` and `pyim` both require `owp-el2org` and `owp-web-server`, but those features are not provided by any package. I suspect that you renamed the respective libraries to `org2web-el2org` and `org2web-webserver` but forgot to update `exwm-x` and `pyim` accordingly.

**Comment by tumashu** [comment]
i am waiting org2web to be merged, after it is merged, i will update all

**Comment by tarsius** [comment]
I assume you are talking about https://github.com/melpa/melpa/pull/4897? I think you should comment on that issue and say that things are ready now (if that is the case).

**Comment by tumashu** [comment]
O, sorry, It has been ready 10 days ago...

**Comment by tumashu** [comment]
fixed.

**Comment by tarsius** [comment]
Thanks!
