### ISSUE TITLE
RFC: Split up in independent packages

### ISSUE THREAD

**Issue by dakra** [tumashu/exwm-x#6]
I "only" use exwm and don't want all the appconfig, buttons etc that exwm-x
provides.

I would like to have the dmenu and quickrun functionality though and I think
other people would like that as well.
So maybe do a more independent `exwm-quickrun` package
and maybe `ivy-dmenu`.
On `ivy-dmenu` someone could define the ivy action like they want,
that way exwm-x just has to require `ivy-dmenu` and set the exwmx specific actions.

**Comment by tumashu** [comment]
Split Exwm-X seem to need much time, for appconfig is the core of exwm-x, which is in everywhere.  at the moment I have no time to do this job ...

**Comment by dakra** [comment]
Understood.

However `exwmx-dmenu` which is the most useful for me
seems to be pretty independent.

I just replaced `exwmx` with `exwm` in `exwmx-dmenu.el` and
changed `exwmx-quickrun` with `start-process-shell-command` and
it works nicely.

If you don't have the time, would you mind if I copy some of
the useful stuff of exwmx and publish them as "independent" packages?

Thanks :)

**Comment by tumashu** [comment]
```
If you don't have the time, would you mind if I copy some of
the useful stuff of exwmx and publish them as "independent" packages?
```
For me, no problem, but you should contact with DarkSun @lujun9972, for exwmx-dmenu is a fork
of el-dmenu :-)

**Comment by tumashu** [comment]
maybe you can  PR el-dmenu to add feature you desired :-)

**Comment by dakra** [comment]
Ah, ok. Didn't realize it's a fork. Should have looked on melpa first. ;)
el-dmenu looks good.

Thanks.
